### PR TITLE
Add rviz files

### PR DESCRIPTION
**Pull request by MoriKen254**
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/21 の一環で，https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/issues/26 を解決したものです．

`cirkit_unit03_viz` への依存を排除しました．

### CODE REVIEW

**Review by forno — DISMISSED** [review]
以下のファイルはもとからあるのは知っているのですが、必要なのでしょうか？

- `rviz/model.rviz`
- `rviz/robot/autorun.rviz`
- `rviz/robot/autorun2.rviz`

変更したファイルに関しては問題なさそうです。

**Comment by forno** [comment]
追記：
grep でも引っかからなかったので依存は完全に取り除けていると思います。

**Comment by RyodoTanaka** [comment]
WARN] [1480496306.045621220]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
Faild to open port: imcs01
[FATAL] [1480496306.052607569]: Could not connect to cirkit unit03.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not connect to cirkit unit03
[INFO] [WallTime: 1480496306.156699] ROS Serial Python Node
[INFO] [WallTime: 1480496306.176595] Connecting to /dev/arduino_uno_95233353131351D040D0 at 57600 baud
[ERROR] [WallTime: 1480496306.180132] Error opening serial: could not open port /dev/arduino_uno_95233353131351D040D0: [Errno 2] No such file or directory: '/dev/arduino_uno_95233353131351D040D0'
[ERROR] [1480496306.261485194]: Exception thrown while opening Hokuyo.
Failed to open port: /dev/sensors/hokuyo_H0807317. No such file or directory (errno = 2). The requested port does not exist. Is the hokuyo connected? Was the port name misspelled? (in hokuyo::laser::open) You may find further details at http://www.ros.org/wiki/hokuyo_node/Troubleshooting
[cirkit_unit03_driver_node-2] process has died [pid 9396, exit code -6, cmd /home/ryodo/workspace/ROS/tsukuba_ws/devel/lib/cirkit_unit03_driver/cirkit_unit03_driver_node __name:=cirkit_unit03_driver_node __log:=/home/ryodo/.ros/log/26f7392e-b6db-11e6-829d-e8b1fc7aab70/cirkit_unit03_driver_node-2.log].
log file: /home/ryodo/.ros/log/26f7392e-b6db-11e6-829d-e8b1fc7aab70/cirkit_unit03_driver_node-2*.log
start parse
/base_scan /base_scan2
input_topics.size(): 2
[ INFO] [1480496306.307687645]: Subscribing to topics	2
base_scan base_scan2 end parse
[ WARN] [1480496306.361424547]: Transformer::setExtrapolationLimit is deprecated and does not do anything
[rossrial_python-3] process has finished cleanly
log file: /home/ryodo/.ros/log/26f7392e-b6db-11e6-829d-e8b1fc7aab70/rossrial_python-3*.log
[ INFO] [1480496306.424475749]: Subscribed to map topic.
[ INFO] [1480496306.596837838]: Received a 1984 X 1984 map @ 0.050 m/pix

[ INFO] [1480496306.670639586]: Initializing likelihood field model; this can take some time on large maps...
[ INFO] [1480496306.753069194]: Done initializing likelihood field model.
[ERROR] [1480496307.009514476]: Exception thrown while opening Hokuyo.
Failed to open port: /dev/sensors/hokuyo_H1101683. No such file or directory (errno = 2). The requested port does not exist. Is the hokuyo connected? Was the port name misspelled? (in hokuyo::laser::open) You may find further details at http://www.ros.org/wiki/hokuyo_node/Troubleshooting

**Comment by MoriKen254** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_apps/pull/12#pullrequestreview-10712100 は直しました．

**Comment by RyodoTanaka** [comment]
上記は、`autorun.launch`実行時です。

**Comment by RyodoTanaka** [comment]
`autorun_gazebo.launch`の時は、プレーン環境だと`timed_roslaunch`が無いというメッセージが出ます。
が、後で対処するので良いと思います。

**Review by RyodoTanaka — COMMENTED** [review]
実行時にエラーが出ますが、
- Rvizの設定ファイルのみ
- Travisを通す前
なので、とりあえずOKとします

**Review by RyodoTanaka — APPROVED** [review]

**Pull request merged**
